### ISSUE TITLE
Change in the order of tlvs should not change the encoded hex

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/smpp_parser#13]
Decoding the following hex pdu results in
 > 00 00 00 31 00 00 00 04 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 14 01 00 02 03 04 14 00 00 01 02 02 04 00 01 01

![image](https://user-images.githubusercontent.com/3499591/36470665-fad75be0-16eb-11e8-98ca-3d6b50cef62d.png)

Encoding the generated json results in the following hex pdu
 > 00 00 00 32 00 00 00 04 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 14 00 00 01 02 14 01 00 02 03 04 02 04 00 02 00 01

Decoding that results in the following json

![image](https://user-images.githubusercontent.com/3499591/36470723-2d79f7c4-16ec-11e8-867b-a8aabf44a44e.png)

**Comment by c-bik** [comment]
To reproduce for unpack path
```` erlang
-ifdef(CONSOLE).

f().
P = <<
      "00 00 00 31 00 00 00 04 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "
      "14 00 00 01 02 "     % {5120,1,[2]}
      "14 01 00 02 03 04 "  % {5121,2,[3,4]}
      "14 02 00 01 05 "     % {5122,1,[5]}
    >>.
B = << <<(list_to_integer([B1,B2], 16))>> || <<B1:8, B2:8, " ">> <= P >>.
rp(smpp_operation:unpack(B)).

-endif.
```
